### ISSUE TITLE
[leo_gateway][cowboy] Upgrade cowboy to 2.2.2

### ISSUE THREAD

**Issue by mocchira** [leo-project/leofs#1007]
The following procedures will be needed to achieve the goal.

### TODO

- [ ] Refactor the code in leo_gateway 
 based on https://ninenines.eu/docs/en/cowboy/2.2/guide/migrating_from_1.0/
- [ ] Refactor the code in leo_gateway 
 based on https://ninenines.eu/docs/en/cowboy/2.2/guide/migrating_from_2.0/
- [ ] Refactor the code in leo_gateway 
 based on https://ninenines.eu/docs/en/cowboy/2.2/guide/migrating_from_2.1/
- [ ] Folk cowboy and apply some patches including in https://github.com/leo-project/cowboy/commits/for-leofs-1.4 branch to deal with some S3-Clients that don't conform HTTP spec

### Note
This task should be done before getting #1006 started in order to avoid the cowboy version conflict.

**Comment by mocchira** [comment]
Note: At first, check the latest cowboy version when you get started this issue.
