### ISSUE TITLE
Support server side encryption (SSE)

### ISSUE THREAD

**Issue by kentarosasaki** [leo-project/leofs#114]
Is there a plan for server side encryption support?
http://aws.typepad.com/aws/2011/10/new-amazon-s3-server-side-encryption.html
http://googlecloudplatform.blogspot.jp/2013/08/google-cloud-storage-now-provides.html

**Comment by mocchira** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/dev/serv-side-encryption.html

**Comment by yosukehara** [comment]
It is listed on [LeoFS Milestones](https://github.com/leo-project/leofs#version-1). We'll implement SSE with v1.4.0.

**Comment by yosukehara** [comment]
In the first step, we're going to implement [Server-Side Encryption with Customer-Provided Keys (SSE-C) ](http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html).

**Comment by mocchira** [comment]
Spec:
- http://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html

Docs for implement:
- Use block_(en|de)crypt with AES 256bit key according to http://erlang.org/doc/man/crypto.html

**Comment by windkit** [comment]
I propose to add several fields in metadata for SSE-C

1. Original Object ETag
2. Original Object Size
2. Key Salted Hash (for verification)

So most operations could be handled without disk read from AVS and minimize code change at `leo_object_storage`, object encryption and decryption happens in `leo_storage`

@mocchira @yosukehara

**Comment by mocchira** [comment]
@windkit 

Can you elaborate

> Original Object ETag
> Original Object Size

how those values contribute to minimizing the code change and disk read from AVS on each operation (GET/PUT/DELETE/HEAD/MULTIPART UPLOAD)?

and also please share the gross sequence (how it works) on each operation for the review.

> Key Salted Hash (for verification)

Let me confirm that it's meant to be hmac for Key + Salt?
then where does the Salt come from? (I think the Salt also should be stored)

Also I've just noticed, while checking the SSEC spec https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html, a sentence "When you upload an object, Amazon S3 uses the encryption key you provide to apply AES-256 encryption to your data and removes the encryption key from memory.".
"removes the encryption key from memory" part can be tough to implement for high-level language including erlang other than low-level ones like C/C++/Rust as there is no way to control the memory (memset should be called to overwrite the encryption key on memory).
To comply with the spec above, we might have to implement the encryption/decryption logic in NIF. what do you think? > @yosukehara @windkit

**Comment by windkit** [comment]
To respond to GET, HEAD, we need to know the ETag and Object Size of the original file.
Both `checksum` and `dsize` are now referred to that on-disk (after encryption), if we are not recording those, we need to decrypt, aka, disk read.

**Comment by windkit** [comment]
I was thinking about salted hashing the key and store it as `$salt$hash`, salt is randomly generated.

In Amazon S3 documentation, they are storing randomly salted HMAC value (probably HMAC with a master rotating key)

**Comment by windkit** [comment]
@mocchira TBH, that looks more like a marketing sentence to me...

Back to the topic, as the key is transferred to `leo_gateway` it is already in Erlang control somewhere, implementing the logic NIF does not seem to solve the problem at all.

And if there is a way to force Erlang GC particular binary, i think that solves the issue already.

**Comment by mocchira** [comment]
@windkit 

> To respond to GET, HEAD, we need to know the ETag and Object Size of the original file.
> Both checksum and dsize are now referred to that on-disk (after encryption), if we are not recording those, we need to decrypt, aka, disk read.

In case of GET, the decryption must happen so that only HEAD can benefit from the original fields right? 

> I was thinking about salted hashing the key and store it as $salt$hash, salt is randomly generated.

OK, I see.

> As the key is transferred to leo_gateway it is already in Erlang control somewhere, implementing the logic NIF does not seem to solve the problem at all.

Right. (or implementing http handling on leo_gateway in NIF but that make no sense)

> And if there is a way to force Erlang GC particular binary, i think that solves the issue already.
We keep the key until we finish replying should be sufficient enough.

AFAIK, no way (only process heap can be GCed) so for now all we can do without any cost is just explicitly documenting that "removes the encryption key from memory" is not implemented yet. Thoughts?

**Comment by mocchira** [comment]
Note:
Even GCed the memory segment including the key, since no memset is invoked at erlang runtime, the key keep residing in somewhere on memory until the same segment will be reused and overwritten. so it's impossible to achieve this spec in any language without having ability to directly control memory.

**Comment by windkit** [comment]
@mocchira 
> In case of GET, the decryption must happen so that only HEAD can benefit from the original fields right?

True.

> AFAIK, no way (only process heap can be GCed) so for now all we can do without any cost is just explicitly documenting that "removes the encryption key from memory" is not implemented yet. Thoughts?

As Amazon S3 does not give a strong promise like "removes the encryption key right away / immediately", I don't think it is good to say that, it gives impression that we are storing customers' keys somewhere.
To me, we are still discarding the key after we are serving the data.

**Comment by mocchira** [comment]
@windkit 

>>In case of GET, the decryption must happen so that only HEAD can benefit from the original fields right?

>True.

then we have to compare the pros/cons on each whether storing the original fields or not

- Storing original fields (size and checksum)
  - Pros
    - Improve the performance and the system resource consumption in case of HEAD
  - Cons
    - size(1+4byte) + checksum(1+4+16byte) = 26 bytes per object additional capacity needed according to 
      - http://erlang.org/doc/apps/erts/erl_ext_dist.html#id100592
      - http://erlang.org/doc/apps/erts/erl_ext_dist.html#id101762
- Not storing original
  - Pros
    - less capacity needed
  - Cons
    - HEAD takes time and consumes the system resource more than the former one

One way to compare the different unit (disk space used, disk iops/bandwidth, network bandwidth, cpu time) is using the cost in public clouds that enable us to normalize those metrics into cost so that how about making a decision based on this? > @windkit @yosukehara

**Comment by mocchira** [comment]
@windkit 

> As Amazon S3 does not give a strong promise like "removes the encryption key right away / immediately", I don't think it is good to say that, it gives impression that we are storing customers' keys somewhere.

Yes we have to take care not to worry users more than necessary so the actual sentence should be considered as much cares as possible.

> To me, we are still discarding the key after we are serving the data.

As stated above comment, from the actual memory POV, it's true the raw key keep residing in memory so if the system was taken over by exploiting other vulnerability and also which allow hackers to peek the user land memory on any offset then there is possibility the key being leaked. so at very least we have to tell users this kind of risk is existing even if it's almost unlikely to happen.

**Comment by mocchira** [comment]
Reference SSE-C Impl on minio: https://github.com/minio/minio/blob/master/cmd/encryption-v1.go

**Comment by yosukehara** [comment]
@mocchira Thanks for sharing your comment. Let me ask you to share the draft design of the implementation.

**Comment by mocchira** [comment]
The rational behind the impl on minio can be found on https://github.com/minio/sio/blob/master/DARE.md. Now I'm checking its correctness.

**Comment by yosukehara** [comment]
@mocchira 

> then we have to compare the pros/cons on each whether storing the original fields or not

Even if metadata's size little bit increases, I recommend **storing original fields (size and checksum)** because LeoFS' implementation keeps simplicity, and we can expect HEAD performance.

**Comment by yosukehara** [comment]
@mocchira Thanks for sharing `minio/sio/blob/master/DARE.md`

I've read [Data At Rest Encryption (DARE) - Version 1.0](https://github.com/minio/sio/blob/master/DARE.md), and then recognized that it is a suitable implementation for LeoFS' object encryption (client-side) feature:

> "DARE provides confidentiality and integrity of the encrypted data as long as the encryption key is never reused. This means that a different encryption key must be used for every data stream. See Appendix A for recommendations.
>
> DARE needs a unique encryption key per data stream. The best approach to ensure that the keys are unique is to derive every encryption key from a master key."

**Comment by mocchira** [comment]
As for whether storing the original size and checksum,
Since we've decided to adopt the requirement that **"An attacker is defined as somebody who has full access to the encrypted data but not to the encryption key. An attacker can also act as storage provider."** cited from DARE spec, storing the original checksum(md5) and its size could allow attackers to derive the original content by simply brute force attack based on the size and checksum (however ONLY in case its size is very small). so we have to prevent from storing those values on metadata for security.

> The rational behind the impl on minio can be found on https://github.com/minio/sio/blob/master/DARE.md. Now I'm checking its correctness.

It looks great however I feel it's a little overkill (which is designed for the large data streams) to LeoFS as we split the large object into small chunks by ourselves. so I'd like to propose to reject it, instead we can only mimic https://github.com/minio/minio/blob/master/cmd/encryption-v1.go part while using raw AES through https://github.com/leo-project/leo_commons/blob/develop/src/leo_ssec.erl instead of DARE (sio).

**Comment by mocchira** [comment]
## Design Draft and TODO for SSE-C on LeoFS
### Spec
- https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html
### Prerequisites
- LeoFS can be deployed on untrusted storage providers
  - Never storing the original checksum and size on metadata for security
  - for more details: https://github.com/leo-project/leofs/issues/114#issuecomment-362191742
- The risk described on https://github.com/leo-project/leofs/issues/114#issuecomment-361783783 exists unless the erlang runtime supports sort of Secure String implemented in .NET https://msdn.microsoft.com/en-us//library/system.security.securestring(v=vs.110).aspx so that should be explicitly documented 
### Reference IMPL
- https://github.com/minio/minio/blob/master/cmd/encryption-v1.go
  - however DARE (sio) is not needed, instead using raw AES as described above
### TODO
#### IMPL
- [ ] Fix leo_ssec to deal with IV for functions related to encrypt|decrypt
- [ ] Add high level encrypt/decrypt functions to leo_ssec on top of existing (block|stream)_(encrypt|decrypt)_data in order to mimic https://github.com/minio/minio/blob/master/cmd/encryption-v1.go
- [ ] Add fields to metadata in order to store IV and Sealed Key
- [ ] Add metadata convert logic into leo_object_storage by following the existing convention
- [ ] Fix leo_gateway and leo_storage based on new leo_ssec and leo_object_storage
#### TEST
- [ ] Add test cases for as much leofs_client_tests as possible (except clients not supporting SSE-C)
- [ ] UT/IT
- [ ] Test migration from previous versions to 1.4.0 since the metadata format will be bumped
#### Others
- [ ] Documentation

@yosukehara @windkit let me know if you have any question.

**Comment by windkit** [comment]
@mocchira if you are thinking about brute force with original size and original md5, I would rather brute force the encryption key, which is only 256-bit......
with the same rationale, we need to think about how to securely store the key checksums for verification.

**Comment by mocchira** [comment]
@windkit it's impossible to BFA against 256bit (check https://crypto.stackexchange.com/questions/1145/how-much-would-it-cost-in-u-s-dollars-to-brute-force-a-256-bit-key-in-a-year) OTOH, the size of an object which is supposed to encrypt could be more smaller ranging from 1 byte to theoretical limit around 10 bytes according to https://en.wikipedia.org/wiki/Brute-force_attack#Theoretical_limits.

**Comment by yosukehara** [comment]
@mocchira I've reviewed [this comment](https://github.com/leo-project/leofs/issues/114#issuecomment-362204133). I agree with your proposal. We can finally start its implementation.

**Comment by windkit** [comment]
## Status Update
Basic Implementation of SSEC PUT/GET (small object only, key verification skipped)
https://github.com/windkit/leofs/tree/ssec

## Related PR
https://github.com/leo-project/leo_object_storage/pull/28
https://github.com/leo-project/leo_commons/pull/13

**Comment by windkit** [comment]
# TODO
## Cache Handling
I think we would cache encrypted one for data privacy

## Range Get Handling
### Handle at leo_gateway
Pros:
1. Do not need to send the key around
Cons:
1. Increased Traffic

**Comment by yosukehara** [comment]
@windkit 

> I would just copy to here for discussion then
>
>> yes, I have also thought about it, decrypt at leo_storage could be better for performance.
>> 
>> But decrypting at leo_storage means we have to send the key around, is the rpc traffic in Erlang encrypted? Sending keys around is one issue, sending them in plain text is a big one.
>
> looks like we can do over TLS
> https://www.erlang-solutions.com/blog/erlang-distribution-over-tls.html
> 
> do you have any idea about the performance overhead?

We need to consider its implementation way which includes your concern. We're going to share its design later.

**Comment by mocchira** [comment]
Reference: https://issues.apache.org/jira/browse/CASSANDRA-7922

It's a little bit different from the goal of the issue but we may have to encrypt not only files uploaded by users but also any other files used by LeoFS at rest in order to cover more strict compliance needs as described on the above link.
